/**
 * Which ocean(s) an island sits in, or a sea belongs to.
 *
 * Derived from the article's coordinates with a few coarse boxes, then
 * corrected by hand where the boxes are wrong: archipelagos that straddle two
 * oceans (most of Indonesia), marginal seas whose basin assignment follows the
 * IHO rather than the map (Hudson Bay is Arctic), and bodies of water with no
 * ocean at all (the Caspian). Both the boxes and the overrides live here so a
 * bad classification is a one-line fix, and `npm run validate` fails if any
 * island or sea ends up with no ocean and no explanation.
 *
 * Multiple oceans are allowed and are the honest answer for a straddler:
 * Java is accepted for both "in the Indian Ocean" and "in the Pacific Ocean".
 */

export const OCEANS = ['Pacific', 'Atlantic', 'Indian', 'Arctic', 'Southern'];

/** Coarse first pass from a centroid. */
export function oceansFromCoordinates(lat, lon) {
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) return []; // no article coordinates
  if (lat <= -60) return ['Southern'];
  if (lat >= 66.5) return ['Arctic'];
  if (lon >= 100 || lon <= -100) return ['Pacific'];
  if (lon > -100 && lon <= -70 && lat < 8) return ['Pacific']; // Galápagos, Chile
  if (lon > 20 && lon < 100 && lat < 30) return ['Indian'];
  return ['Atlantic'];
}

/**
 * Hand corrections, by entry id. An empty array means "no ocean" and is only
 * legal here, never by omission.
 */
export const OCEAN_OVERRIDES = {
  // --- islands: Indonesia and neighbours straddle the Indian/Pacific line ---
  'island-sumatra': ['Indian', 'Pacific'],
  'island-java': ['Indian', 'Pacific'],
  'island-bali': ['Indian', 'Pacific'],
  'island-lombok': ['Indian', 'Pacific'],
  'island-sumbawa': ['Indian', 'Pacific'],
  'island-sumba': ['Indian'],
  'island-flores': ['Indian', 'Pacific'],
  'island-komodo': ['Indian', 'Pacific'],
  'island-timor': ['Indian', 'Pacific'],
  'island-nias': ['Indian'],
  'island-christmas-island': ['Indian'],
  'island-penang-island': ['Indian'], // Strait of Malacca
  'island-langkawi': ['Indian'],
  'island-phuket': ['Indian'],

  // --- islands: Australia / New Zealand, between the Pacific and the Southern ---
  'island-tasmania': ['Pacific', 'Southern'],
  'island-bruny-island': ['Pacific', 'Southern'],
  'island-kangaroo-island': ['Southern', 'Indian'],
  'island-rottnest-island': ['Indian'],
  'island-stewart-island': ['Pacific', 'Southern'],
  'island-south-island': ['Pacific', 'Southern'],
  'island-new-zealand': ['Pacific', 'Southern'], // as its South Island
  'island-indonesia': ['Pacific', 'Indian'], // Sumatra and Java face the Indian Ocean

  // --- islands: Atlantic/Arctic and Atlantic/Southern edges ---
  'island-greenland': ['Arctic', 'Atlantic'],
  'island-southampton-island': ['Arctic', 'Atlantic'], // Hudson Bay / Foxe Basin - the straddle the sea cohort's own Hudson Bay row uses (the 2026-09-18 islands audit)
  'island-iceland': ['Atlantic', 'Arctic'],
  'island-south-georgia': ['Atlantic', 'Southern'],
  'island-bouvet-island': ['Atlantic', 'Southern'],
  'island-tierra-del-fuego': ['Atlantic', 'Pacific'],
  'island-east-falkland': ['Atlantic'],
  'island-west-falkland': ['Atlantic'],

  // --- islands whose article has no coordinates ---
  'island-ibiza': ['Atlantic'],
  'island-saint-croix': ['Atlantic'],
  'island-grand-bahama': ['Atlantic'],
  'island-sal': ['Atlantic'],
  'island-waiheke-island': ['Pacific'],

  // --- Norwegian Sea islands sit on the Atlantic/Arctic line ---
  'island-senja': ['Atlantic', 'Arctic'],
  'island-hinnoya': ['Atlantic', 'Arctic'],

  // --- islands in lakes: no ocean at all ---
  'island-ometepe': [],
  'island-isle-royale': [],
  'island-mackinac-island': [],

  // --- seas whose article has no coordinates ---
  'sea_ocean-wadden-sea': ['Atlantic'],

  // --- seas with no ocean (endorheic) ---
  'sea_ocean-caspian-sea': [],
  'sea_ocean-aral-sea': [],
  'sea_ocean-dead-sea': [],

  // --- seas: basin assignment where the box gets it wrong ---
  'sea_ocean-hudson-bay': ['Arctic', 'Atlantic'],
  'sea_ocean-norwegian-sea': ['Atlantic', 'Arctic'],
  'sea_ocean-greenland-sea': ['Arctic', 'Atlantic'],
  'sea_ocean-white-sea': ['Arctic'],
  'sea_ocean-scotia-sea': ['Southern', 'Atlantic'],
  'sea_ocean-southern-ocean': ['Southern'],
  'sea_ocean-timor-sea': ['Indian'],
  'sea_ocean-arafura-sea': ['Pacific', 'Indian'],
  'sea_ocean-savu-sea': ['Indian', 'Pacific'],
  'sea_ocean-great-australian-bight': ['Indian', 'Southern'],
  'sea_ocean-gulf-of-carpentaria': ['Pacific', 'Indian'],
  'sea_ocean-tasman-sea': ['Pacific'],
  'sea_ocean-mozambique-channel': ['Indian'],
  'sea_ocean-andaman-sea': ['Indian'],
  'sea_ocean-bay-of-bengal': ['Indian'],
  'sea_ocean-persian-gulf': ['Indian'],
  'sea_ocean-red-sea': ['Indian'],
  'sea_ocean-mediterranean-sea': ['Atlantic'],
  'sea_ocean-black-sea': ['Atlantic'],
  'sea_ocean-baltic-sea': ['Atlantic'],

  // --- the oceans themselves ---
  'sea_ocean-pacific-ocean': ['Pacific'],
  'sea_ocean-atlantic-ocean': ['Atlantic'],
  'sea_ocean-indian-ocean': ['Indian'],
  'sea_ocean-arctic-ocean': ['Arctic'],

  // --- the Eastern Europe islands (2026-09-18): the Danube, Vistula, Warta, Vltava, Dnieper and Daugava islands and the lake islands (Skadar, Ioannina, Peipus, the Curonian and Szczecin lagoons) in no ocean; six Mediterranean / Black Sea articles without coordinates placed by hand ---
  'island-margaret-island': [],
  'island-hajogyari-island': [],
  'island-great-war-island': [],
  'island-csepel-island': [],
  'island-ostrow-tumski': [],
  'island-sarengrad-island': [],
  'island-great-braila-island': [],
  'island-stvanice': [],
  'island-kipsala': [],
  'island-belene-island': [],
  'island-ostrow-island': [],
  'island-strelecky-island': [],
  'island-lesendro': [],
  'island-trukhaniv-island': [],
  'island-lucavsala': [],
  'island-szentendre-island': [],
  'island-szigetkoz': [],
  'island-zitny-ostrov': [],
  'island-ada-ciganlija': [],
  'island-tataru-mare-island': [],
  'island-ostrow-lednicki': [],
  'island-rusanivka': [],
  'island-piirissaar': [],
  'island-ioannina-island': [],
  'island-rusne-island': [],
  'island-karsibor': [],
  'island-ostriv-velykyi-potomkin': [],
  'island-gyaros': ['Atlantic'],
  'island-tuzla-island': ['Atlantic'],
  'island-ro': ['Atlantic'],
  'island-kalydon': ['Atlantic'],
  'island-scedro': ['Atlantic'],
  'island-gavdopoula': ['Atlantic'],

  // --- the 2026-09-18 seas audit: Foxe Basin and Channel are Arctic like every island in them; Bellot Strait (Northwest Passage), Kempenfelt Bay (Lake Simcoe), two Newfoundland bays placed by hand ---
  'sea_ocean-foxe-basin': ['Arctic'],
  'sea_ocean-foxe-channel': ['Arctic'],
  'sea_ocean-bellot-strait': ['Arctic'],
  'sea_ocean-kempenfelt-bay': [],
  'sea_ocean-st-john-bay': ['Atlantic'],
  'sea_ocean-voisey-s-bay': ['Atlantic'],

  // --- Lake Huron's North Channel and Lake Superior's Thunder Bay are in no ocean (2026-09-18) ---
  'sea_ocean-north-channel-ontario': [],
  'sea_ocean-thunder-bay-ontario': [],

  // --- the Mexico and Canada seas (2026-09-18): the Great Lakes and Ottawa River bays are in no ocean; three articles without coordinates placed by hand ---
  'sea_ocean-georgian-bay': [],
  'sea_ocean-bay-of-quinte': [],
  'sea_ocean-toronto-harbour': [],
  'sea_ocean-hamilton-harbour': [],
  'sea_ocean-nottawasaga-bay': [],
  'sea_ocean-parry-sound': [],
  'sea_ocean-batchawana-bay': [],
  'sea_ocean-shirleys-bay': [],
  'sea_ocean-charleston-harbor': ['Atlantic'],
  'sea_ocean-princess-louisa-inlet': ['Pacific'],
  'sea_ocean-gulf-of-tehuantepec': ['Pacific'],

  // --- the 2026-09-18 islands audit: Lake Michigan / Big Rideau / Powell Lake / Fraser / Kennebecasis / Miramichi / Saint John River islands in no ocean; the Hudson Bay islands straddle Arctic and Atlantic like Southampton and the sea cohort's Hudson Bay; Foxe Basin is Arctic ---
  'island-horseshoe-island-wisconsin': [],
  'island-grindstone-island-ontario': [],
  'island-goat-island-british-columbia': [],
  'island-douglas-island-british-columbia': [],
  'island-kennebecasis-island': [],
  'island-beaubears-island': [],
  'island-bear-island-new-brunswick': [],
  'island-coats-island': ['Arctic', 'Atlantic'],
  'island-mansel-island': ['Arctic', 'Atlantic'],
  'island-flaherty-island': ['Arctic', 'Atlantic'],
  'island-east-pen-island': ['Arctic', 'Atlantic'],
  'island-marble-island': ['Arctic', 'Atlantic'],
  'island-smith-island-nunavut': ['Arctic', 'Atlantic'],
  'island-nagjuttuuq': ['Arctic'],

  // --- the Mexico and Canada island namesakes (2026-09-18): Lake Erie / Huron / Simcoe / Temagami / Okanagan / Ontario and St. Lawrence / Cataraqui islands in no ocean; two BC islands without coordinates ---
  'island-stuart-island-british-columbia': ['Pacific'],
  'island-nelson-island-british-columbia': ['Pacific'],
  'island-middle-island-ontario': [],
  'island-bois-blanc-island-ontario': [],
  'island-rattlesnake-island-british-columbia': [],
  'island-snake-island-ontario': [],
  'island-bear-island-ontario': [],
  'island-grenadier-island-ontario': [],
  'island-big-island-ontario': [],
  'island-hope-island-ontario': [],
  'island-isle-of-man-ontario': [],

  // --- the Mexico and Canada islands (2026-09-18): the Great Lakes, St. Lawrence, Fraser, Okanagan, Chapala, Xochimilco, Manicouagan, Lake Winnipeg and Maligne Lake islands are in no ocean; twelve articles without coordinates placed by hand (the Gulf of California is the Pacific, Ungava Bay the Arctic) ---
  'island-island-of-the-dolls': [],
  'island-island-of-montreal': [],
  'island-rene-levasseur-island': [],
  'island-christian-island': [],
  'island-flowerpot-island': [],
  'island-grosse-isle': [],
  'island-michipicoten-island': [],
  'island-nuns-island': [],
  'island-st-joseph-island': [],
  'island-saint-helen-s-island': [],
  'island-notre-dame-island': [],
  'island-cockburn-island': [],
  'island-ile-bizard': [],
  'island-lulu-island': [],
  'island-amherst-island': [],
  'island-navy-island': [],
  'island-caribou-island': [],
  'island-cornwall-island-ontario': [],
  'island-silver-islet': [],
  'island-fighting-island': [],
  'island-ile-jesus': [],
  'island-beausoleil-island': [],
  'island-howe-island': [],
  'island-zavikon-island': [],
  'island-bigwin-island': [],
  'island-georgina-island': [],
  'island-giants-tomb-island': [],
  'island-main-duck-island': [],
  'island-stag-island-ontario': [],
  'island-isle-aux-grues': [],
  'island-ile-perrot': [],
  'island-barnston-island': [],
  'island-st-ignace-island': [],
  'island-thorah-island': [],
  'island-petrie-island': [],
  'island-simcoe-island': [],
  'island-nicholson-island': [],
  'island-griffith-island': [],
  'island-pie-island': [],
  'island-strawberry-island': [],
  'island-beckwith-island': [],
  'island-hill-island': [],
  'island-massacre-island': [],
  'island-ile-parisienne': [],
  'island-kelvin-island': [],
  'island-mitchell-island': [],
  'island-barrie-island': [],
  'island-chantry-island': [],
  'island-fawn-island': [],
  'island-grant-island': [],
  'island-isla-de-los-alacranes': [],
  'island-temagami-island': [],
  'island-waupoos-island': [],
  'island-ile-aux-oies': [],
  'island-dowker-island': [],
  'island-porphyry-island': [],
  'island-annacis-island': [],
  'island-westham-island': [],
  'island-kirkland-island': [],
  'island-mcmillan-island': [],
  'island-reindeer-island': [],
  'island-spirit-island': [],
  'island-pender-island': ['Pacific'],
  'island-cortes-island': ['Pacific'],
  'island-san-benedicto-island': ['Pacific'],
  'island-akpatok-island': ['Arctic'],
  'island-sonora-island': ['Pacific'],
  'island-langara-island': ['Pacific'],
  'island-isla-santa-catalina': ['Pacific'],
  'island-isla-del-carmen': ['Pacific'],
  'island-pearse-island': ['Pacific'],
  'island-isla-coronado': ['Pacific'],
  'island-north-harbour-island': [], // Lake Erie (the 2026-09-18 islands audit)
  'island-isla-coronados': ['Pacific'],

  // --- 2026-09-17 pre-merge integrity audit: 21 pre-wave islands in lakes and rivers (the Seine, the Tiber, Lake Bled, Lake Van, the Chiemsee, the Dnieper, the Han, the Chao Phraya, the Brahmaputra, the Kaveri, the Nile at Cairo, Lake Malawi, Lake Kivu, Lake Victoria, Lake Titicaca, Lake Peten Itza, Lake Rotorua, Lake Baikal, the St. Lawrence) carried an ocean by the coordinate box ---
  'island-ile-de-la-cite': [],
  'island-ile-saint-louis': [],
  'island-tiber-island': [],
  'island-bled-island': [],
  'island-akdamar-island': [],
  'island-herreninsel': [],
  'island-khortytsia': [],
  'island-yeouido': [],
  'island-ko-kret': [],
  'island-majuli': [],
  'island-srirangam': [],
  'island-umananda': [],
  'island-gezira': [],
  'island-likoma': [],
  'island-idjwi': [],
  'island-migingo': [],
  'island-isla-del-sol': [],
  'island-isla-de-flores': [],
  'island-mokoia': [],
  'island-olkhon': [],
  'island-thousand-islands': [],

  // --- 2026-09-17 islands audit: 25 wave islands in lakes and rivers (the Thousand Islands, Sandusky Bay, Lake Ontario, Lake Erie, the St. Clair River, Crater Lake, Lake George FL, American Lake, St. George Lake, the Mississippi, the Tennessee, the Columbia, the Delta, Saimaa, Lough Derg, Malaren, Vanern, Riddarfjarden, Mjosa, the Ermal reservoir, Loch Olabhat) and four pre-wave Great Lakes rows carried an ocean ---
  'island-just-room-enough-island': [],
  'island-wellesley-island': [],
  'island-johnson-s-island': [],
  'island-stony-island': [],
  'island-starve-island': [],
  'island-russell-island': [],
  'island-wizard-island': [],
  'island-drayton-island': [],
  'island-silcox-island': [],
  'island-hawaii-2': [],
  'island-mosenthein-island': [],
  'island-hobbs-island': [],
  'island-clover-island': [],
  'island-tinsley-island': [],
  'island-brannan-island': [],
  'island-saaminginsalo': [],
  'island-soisalo': [],
  'island-inis-cealtra': [],
  'island-lovon': [],
  'island-selaon': [],
  'island-torso': [],
  'island-riddarholmen': [],
  'island-helgoya': [],
  'island-ermal-island': [],
  'island-eilean-domhnuill': [],
  'island-goat-island-new-york': [],
  'island-south-bass-island': [],
  'island-apostle-islands': [],
  'island-devils-island': [],

  // --- US no-figure islands re-run (2026-09-17): ten articles without coordinates, placed by hand (Sea Island GA, Heart Island NY (Boldt Castle), Enders CT, Bloodsworth MD, Summerland Key FL, Long Beach Barrier Island NY, Nixes Mate MA, Ragged Island ME on the Atlantic; Allan Island WA and Sutwik Island AK on the Pacific) ---
  'island-sea-island-georgia': ['Atlantic'],
  'island-heart-island': [], // the Thousand Islands, St. Lawrence River (2026-09-17 audit)
  'island-enders-island': ['Atlantic'],
  'island-bloodsworth-island': ['Atlantic'],
  'island-summerland-key': ['Atlantic'],
  'island-allan-island': ['Pacific'],
  'island-long-beach-barrier-island': ['Atlantic'],
  'island-nixes-mate': ['Atlantic'],
  'island-ragged-island': ['Atlantic'],
  'island-sutwik-island': ['Pacific'],

  // --- US no-figure islands re-run (2026-09-17): islands in lakes and rivers have no ocean ---
  'island-volvo-island': [],
  'island-rattlesnake-island-ohio': [],
  'island-harsens-island': [],
  'island-dark-island': [],
  'island-blennerhassett-island': [],
  'island-luna-island': [],
  'island-isle-la-motte': [],
  'island-wheeling-island': [],
  'island-charity-island': [],
  'island-grindstone-island': [],
  'island-government-island': [],
  'island-constitution-island': [],
  'island-doty-island': [],
  'island-stansbury-island': [],
  'island-calumet-island': [],
  'island-manitou-island': [],
  'island-poverty-island': [],
  'island-ballast-island': [],
  'island-chouteau-island': [],
  'island-blakeley-island': [],
  'island-summer-island': [],
  'island-unity-island': [],
  'island-artificial-island': [],
  'island-latsch-island': [],
  'island-negit-island': [],
  'island-van-schaick-island': [],
  'island-virginius-island': [],
  'island-blaine-island': [],
  'island-buffington-island': [],
  'island-middle-island-michigan': [],
  'island-stockton-island': [],
  'island-whiskey-island': [],
  'island-big-st-martin-island': [],
  'island-buckeye-island': [],
  'island-campbell-s-island': [],
  'island-carleton-s-prize': [],
  'island-grand-tower-island': [],
  'island-granite-island': [],
  'island-powder-house-island': [],

  // --- Muuratsalo is in Lake Paijanne ---

  // --- nordic-islands 2026-09-17: lake islands (Malaren, Vanern, Vattern, Saimaa, Paijanne, Mjosa...) are in no ocean; two without coordinates placed by hand ---
  'island-nekselo': ['Atlantic'],
  'island-froson': [],
  'island-adelso': [],
  'island-kallandso': [],
  'island-kungsholmen': [],
  'island-kungshatt': [],

  // --- Dragonera (Mallorca) has no page coordinate ---
  'island-dragonera': ['Atlantic'],

  // --- it-es-islands 2026-09-17: the Maggiore, Garda, Orta and Guadalquivir islands are in no ocean ---
  'island-isola-bella': [],
  'island-isola-del-garda': [],
  'island-isola-madre': [],
  'island-isola-dei-pescatori': [],
  'island-san-giulio-island': [],
  'island-castelli-di-cannero': [],
  'island-isla-de-la-cartuja': [],

  // --- fr-islands 2026-09-17: Seine, Loire and IJsselmeer islands are in no ocean ---
  'island-ile-de-nantes': [],
  'island-ile-des-impressionnistes': [],
  'island-ile-saint-germain': [],
  'island-ile-de-la-jatte': [],
  'island-flevopolder': [],
  'island-ijsselmonde': [],
  'island-hoeksche-waard': [],

  // --- Donauinsel is a Danube island in Vienna ---
  'island-donauinsel': [],

  // --- uk-islands: Loch Lomond, Lough Erne, Loch Awe and Loch Earn islands are in no ocean ---
  'island-inchmurrin': [],
  'island-inchconnachan': [],
  'island-inchgalbraith': [],
  'island-boa-island': [],
  'island-lusty-beg-island': [],
  'island-inishail': [],
  'island-neish-island': [],

  // --- uk-islands 2026-09-17: lake, loch, lough and Thames islands are in no ocean; nine without coordinates placed by hand ---
  'island-eel-pie-island': [],
  'island-tagg-s-island': [],
  'island-monkey-island-county-wicklow': [],
  'island-magna-carta-island': [],
  'island-peel-island': [],
  'island-ram-s-island': [],
  'island-thames-ditton-island': [],
  'island-temple-island': [],
  'island-desborough-island': [],
  'island-ash-island': [],
  'island-isle-maree': [],
  'island-oliver-s-island': [],
  'island-raven-s-ait': [],
  'island-alney-island': [],
  'island-fraoch-eilean': [],
  'island-isleworth-ait': [],
  'island-trowlock-island': [],
  'island-corporation-island': [],
  'island-fry-s-island': [],
  'island-glover-s-island': [],
  'island-ham-island': [],
  'island-hamhaugh-island': [],
  'island-eilean-subhainn': [],
  'island-fota-island': ['Atlantic'],
  'island-whiddy-island': ['Atlantic'],
  'island-north-ronaldsay': ['Atlantic'],
  'island-horsea-island': ['Atlantic'],
  'island-blackrock-island': ['Atlantic'],
  'island-hinba': ['Atlantic'],

  // --- 2026-09-16 US islands audit: islands in lakes and rivers (Great Lakes, Great Salt Lake, Tahoe, Mono, Flathead, Okeechobee, Champlain, Sebago, Pyramid, Devils Lake, Bay Lake; Mississippi, Ohio, St. Lawrence, Detroit, St. Marys, Niagara, Hudson at Troy, Columbia, Sacramento-San Joaquin Delta, Potomac, Chicago River, Taku) have no ocean; the last nine are pre-wave rows of the same class ---
  'island-zug-island': [],
  'island-bois-blanc-island-michigan': [],
  'island-grand-island-new-york': [],
  'island-antelope-island': [],
  'island-washington-island-wisconsin': [],
  'island-sauvie-island': [],
  'island-fannette-island': [],
  'island-sugar-island-michigan': [],
  'island-north-manitou-island': [],
  'island-fremont-island': [],
  'island-round-island-michigan': [],
  'island-wild-horse-island': [],
  'island-grosse-ile': [],
  'island-south-manitou-island': [],
  'island-chambers-island': [],
  'island-middle-bass-island': [],
  'island-neebish-island': [],
  'island-valcour-island': [],
  'island-carleton-island': [],
  'island-garden-island': [],
  'island-high-island-michigan': [],
  'island-paoha-island': [],
  'island-puget-island': [],
  'island-hog-island-michigan': [],
  'island-galloo-island': [],
  'island-marquette-island': [],
  'island-sherman-island': [],
  'island-grenadier-island-new-york': [],
  'island-selden-island': [],
  'island-diamond-island': [],
  'island-amygdaloid-island': [],
  'island-carrington-island': [],
  'island-croil-island': [],
  'island-galop-island': [],
  'island-grahams-island': [],
  'island-nine-mile-island': [],
  'island-browns-island': [],
  'island-canyon-island': [],
  'island-discovery-island-florida': [],
  'island-goose-island-illinois': [],
  'island-frye-island': [],
  'island-green-island-new-york': [],
  'island-hayden-island': [],
  'island-bethel-island': [],
  'island-north-bass-island': [],
  'island-french-island': [],
  'island-davis-island': [],
  'island-detroit-island': [],
  'island-anaho-island': [],
  'island-bradford-island': [],
  'island-kreamer-island': [],
  'island-lowes-island': [],
  'island-ryer-island': [],
  'island-ritta-island': [],
  'island-lime-island': [],
  'island-mcdonald-island': [],
  'island-bouldin-island': [],
  'island-jones-tract': [],
  'island-mandeville-island': [],
  'island-van-sickle-island': [],
  'island-venice-island': [],
  'island-quimby-island': [],
  'island-twitchell-island': [],
  'island-woodward-island': [],
  'island-hastings-tract': [],
  'island-atlas-tract': [],
  'island-moore-tract': [],
  'island-manitoulin': [],
  'island-wolfe-island': [],
  'island-pelee-island': [],
  'island-toronto-islands': [],
  'island-kelleys-island': [],
  'island-beaver-island': [],
  'island-madeline-island': [],
  'island-belle-isle-michigan': [],
  'island-mercer-island': [],

  // --- 2026-09-16 US islands (2): Morgan Island, South Carolina (no article coordinates) ---
  'island-morgan-island': ['Atlantic'],

  // --- 2026-09-16 US islands: articles without coordinates (the Northern Marianas chain, Alaskan and Carolina islands; Credit Island is in the Mississippi, Gunnison Island in the Great Salt Lake) ---
  'island-anatahan': ['Pacific'],
  'island-gardner-pinnacles': ['Pacific'],
  'island-annette-island': ['Pacific'],
  'island-agrihan': ['Pacific'],
  'island-alamagan': ['Pacific'],
  'island-farallon-de-pajaros': ['Pacific'],
  'island-harstine-island': ['Pacific'],
  'island-asuncion-island': ['Pacific'],
  'island-guguan': ['Pacific'],
  'island-sarigan': ['Pacific'],
  'island-aguiguan': ['Pacific'],
  'island-etolin-island': ['Pacific'],
  'island-popof-island': ['Pacific'],
  'island-chamisso-island': ['Arctic'],
  'island-folly-island': ['Atlantic'],
  'island-capers-island': ['Atlantic'],
  'island-mills-island': ['Atlantic'],
  'island-credit-island': [],
  'island-gunnison-island': [],

  // --- more coordinate-less islands (2026-09-15 expansion) ---
  'island-tobago': ['Atlantic'],
  'island-lamma-island': ['Pacific'],
  'island-bantayan': ['Pacific'],
  'island-con-dao': ['Pacific'],
  'island-ko-chang': ['Pacific'],
  'island-ko-kut': ['Pacific'],
  'island-weh': ['Indian'],
  'island-lembeh': ['Pacific'],
  'island-nusakambangan': ['Indian'],
  'island-talaud-islands': ['Pacific'],
  'island-kai-islands': ['Pacific', 'Indian'],
  'island-minicoy': ['Indian'],
  'island-vypin': ['Indian'],
  'island-nijhum-dwip': ['Indian'],
  'island-ramree': ['Indian'],
  'island-cheduba': ['Indian'],

  // --- islands and seas whose article has no coordinates (2026-09-15 expansion) ---
  'island-ashuradeh': [],
  'island-bugala': [],
  'island-yas-island': ['Indian'],
  'island-saadiyat': ['Indian'],
  'island-graham-island-british-columbia': ['Pacific'],
  'island-baranof-island': ['Pacific'],
  'island-molokini': ['Pacific'],
  'island-taboga': ['Pacific'],
  'island-matiu-somes-island': ['Pacific'],
  'island-rotuma': ['Pacific'],
  'island-aneityum': ['Pacific'],
  'island-mare-indonesia': ['Pacific'],
  'island-rongelap': ['Pacific'],
  'island-manono': ['Pacific'],
  'island-pagan': ['Pacific'],
  'island-rurutu': ['Pacific'],
  'island-rapa-iti': ['Pacific'],
  'island-atiu': ['Pacific'],
  'island-shikotan': ['Pacific'],
  'island-paramushir': ['Pacific'],
  'island-kuchinoerabu': ['Pacific'],
  'island-niijima': ['Pacific'],
  'island-kozushima': ['Pacific'],
  'island-miyakejima': ['Pacific'],
  'island-hahajima': ['Pacific'],
  'island-orchid-island': ['Pacific'],
  'island-weizhou': ['Pacific'],
  'island-changdao': ['Pacific'],
  'island-wando': ['Pacific'],
  'island-ocracoke': ['Atlantic'],
  'island-merritt-island': ['Atlantic'],
  'island-saint-barthelemy': ['Atlantic'],
  'sea_ocean-strait-of-malacca': ['Indian', 'Pacific'],
  'sea_ocean-firth-of-forth': ['Atlantic'],
  'sea_ocean-firth-of-clyde': ['Atlantic'],
  'sea_ocean-bay-of-pomerania': ['Atlantic'],
  'sea_ocean-szczecin-lagoon': ['Atlantic'],

  // --- islands whose article has no coordinates (2026-09-14 expansion) ---
  'island-favignana': ['Atlantic'],
  'island-isla-de-lobos': ['Atlantic'],
  'island-desertas-islands': ['Atlantic'],
  'island-brac': ['Atlantic'],
  'island-dugi-otok': ['Atlantic'],
  'island-amrum': ['Atlantic'],
  'island-fohr': ['Atlantic'],
  'island-south-sandwich-islands': ['Southern', 'Atlantic'],
  'island-monte-isola': [],

  // --- the US no-figure seas re-run (2026-09-17): bays and straits of the Great Lakes, Lake Washington and Lake Union are in no ocean, as the lake islands ---
  'sea_ocean-straits-of-mackinac': [],
  'sea_ocean-whitefish-bay': [],
  'sea_ocean-green-bay': [],
  'sea_ocean-porte-des-morts': [],
  'sea_ocean-grand-traverse-bay': [],
  'sea_ocean-saginaw-bay': [],
  'sea_ocean-chequamegon-bay': [],
  'sea_ocean-thunder-bay-michigan': [],
  'sea_ocean-sandusky-bay': [],
  'sea_ocean-presque-isle-bay': [],
  'sea_ocean-sturgeon-bay': [],
  'sea_ocean-irondequoit-bay': [],
  'sea_ocean-little-traverse-bay': [],
  'sea_ocean-sodus-bay': [],
  'sea_ocean-big-bay-de-noc': [],
  'sea_ocean-little-bay-de-noc': [],
  'sea_ocean-anchor-bay': [],
  'sea_ocean-portage-bay': [],
  'sea_ocean-salmon-bay': [],
  // --- the namesakes of decision 5 (2026-09-18): islands in lakes and rivers (Winnipesaukee, Lake Michigan, Lake Superior, Lake Erie, Moosehead, Champlain, Mindemoya, Lough Neagh, Lough Erne; the Detroit, St. Lawrence, Hudson, Willamette and Thames) are in no ocean; three articles without coordinates placed by hand ---
  'island-governors-island-new-hampshire': [],
  'island-bear-island-new-hampshire': [],
  'island-st-martin-island': [],
  'island-fox-islands-michigan': [],
  'island-plum-island-wisconsin': [],
  'island-rock-island': [],
  'island-washington-island-michigan': [],
  'island-sugar-island-ohio': [],
  'island-fox-island-michigan': [],
  'island-deer-island-new-york': [],
  'island-iona-island-new-york': [],
  'island-treasure-island-ontario': [],
  'island-sugar-island-maine': [],
  'island-grand-isle-vermont': [],
  'island-ross-island-oregon': [],
  'island-coney-island-lough-neagh': [],
  'island-white-island-county-fermanagh': [],
  'island-formosa-island': [],
  'island-sanak-island': ['Pacific'],
  'island-hog-island-rhode-island': ['Atlantic'],
  'island-goose-island-new-york': ['Atlantic'],
  'island-marsh-island-maine': [], // Orono's island between the Penobscot and the Stillwater (the 2026-09-18 data audit)

  // coastal bays whose coordinates fall outside every ocean box
  'sea_ocean-magens-bay': ['Atlantic'],
  'sea_ocean-coos-bay': ['Pacific'],
  'sea_ocean-oregon-inlet': ['Atlantic'],
  'sea_ocean-lake-worth-lagoon': ['Atlantic'],
  'sea_ocean-chef-menteur-pass': ['Atlantic'],

  // --- the East Asia islands (2026-09-19): river and lake islands in no ocean (the Ussuri, Amur and Argun
  // border islands, the Taedong, Yalu and Pearl River islands, Lake Biwa's Okishima, Lake Tai's Xishan,
  // the Han's Namiseom); 24 Japanese and Korean articles without coordinates are the Pacific's ---
  'island-zhenbao-island': [],
  'island-bolshoy-ussuriysky-island': [],
  'island-yinlong-island': [],
  'island-abagaitu-islet': [],
  'island-namiseom': [],
  'island-rungrado': [],
  'island-yanggakdo': [],
  'island-hwanggumpyong-island': [],
  'island-wihwa-island': [],
  'island-shamian': [],
  'island-ersha-island': [],
  'island-haixinsha-island': [],
  'island-changzhou-island': [],
  'island-zhongshan-island': [],
  'island-nantai-island': [],
  'island-okishima': [],
  'island-xishan-island': [],
  'island-guanzhou-island': [], // Haizhu's Pearl River island (the 2026-09-19 audit)
  'island-minamidaitojima': ['Pacific'],
  'island-hachijo-kojima': ['Pacific'],
  'island-mageshima': ['Pacific'],
  'island-mikura-jima': ['Pacific'],
  'island-awashima-island': ['Pacific'],
  'island-okidaitojima': ['Pacific'],
  'island-zhifu-island': ['Pacific'],
  'island-kitadaitojima': ['Pacific'],
  'island-suwanosejima': ['Pacific'],
  'island-takarajima': ['Pacific'],
  'island-irabu-island': ['Pacific'],
  'island-nakanoshima-kagoshima': ['Pacific'],
  'island-engetsu-island': ['Pacific'],
  'island-hashira-island': ['Pacific'],
  'island-ikema-island': ['Pacific'],
  'island-izena-island': ['Pacific'],
  'island-mishima-island': ['Pacific'],
  'island-akusekijima': ['Pacific'],
  'island-cheongsando': ['Pacific'],
  'island-kuchinoshima': ['Pacific'],
  'island-genkai-island': ['Pacific'],
  'island-hario-island': ['Pacific'],
  'island-tobishima': ['Pacific'],
  'island-oshima-ehime': ['Pacific'],
  // --- the East Asia seas (2026-09-19): four bays and straits without coordinates, all the Pacific's ---
  'sea_ocean-mutsu-bay': ['Pacific'],
  'sea_ocean-uchiura-bay': ['Pacific'],
  'sea_ocean-daya-bay': ['Pacific'],
  'sea_ocean-qiongzhou-strait': ['Pacific'],
};

/** Final answer for one entry. */
export function oceansFor(entry) {
  if (entry.id in OCEAN_OVERRIDES) return OCEAN_OVERRIDES[entry.id];
  return oceansFromCoordinates(entry.lat, entry.lon);
}
